version: '3'
services:
  web:
    build: .
    ports:
      - "8080"
    depends_on:
      - db
  tests:
    build:
      context: .
      dockerfile: tests.dockerfile
    volumes:
      - .:/project
    working_dir: /project
    depends_on:
      - web
  db:
    image: "postgres:13-alpine"
    environment:
        POSTGRES_DB: gowebtem
        POSTGRES_USER: gowebtem
        POSTGRES_PASSWORD: gowebtem